TARGET_DIR = "target"
MANIFEST_FILE_NAME = "manifest.json"

PARSE_DIRECTORIES_IGNORE = ["target", "^[/.]+"]

COMPILED_GRAPH_FIG_PATH_NODES = "dag_compile.png"
COMPILED_GRAPH_FIG_PATH_RUN = "dag_run.png"
COMPILED_GRAPH_FIG_PATH_AGENTS = "dag_agents.png"

LOG_FILE = "logs/dlo.log"

DEFAULT_CURSOR_LIMIT = 100_000
DEFAULT_AGENT_RECURSION_LIMIT = 100
